services:
  postgres:
    container_name: postgres
    image: library/postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
      TZ: GMT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "testdb"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:


